name: Terraform Apply

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::078591672268:role/PlatformCIExecutionRole
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Dev Network
        run: |
          cd envs/dev/01-network
          terraform init
          terraform apply -auto-approve

      - name: Dev EKS
        run: |
          cd envs/dev/02-eks
          terraform init
          terraform apply -auto-approve

      - name: Dev Platform
        run: |
          cd envs/dev/03-platform
          terraform init
          terraform apply -auto-approve

      - name: Dev Observability
        run: |
          cd envs/dev/04-observability
          terraform init
          terraform apply -auto-approve
