name: Terraform UAT Apply

on:
#  push:
#    branches:
#      - main
  workflow_dispatch:
  
permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::078591672268:role/PlatformCIExecutionRole
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Uat Network
        run: |
          cd envs/uat/01-network
          terraform init
          terraform apply -auto-approve

      - name: Uat EKS
        run: |
          cd envs/uat/02-eks
          terraform init
          terraform apply -auto-approve

      - name: Uat Platform
        run: |
          cd envs/uat/03-platform
          terraform init
          terraform apply -auto-approve

      - name: Uat Observability
        run: |
          cd envs/uat/04-observability
          terraform init
          terraform apply -auto-approve

      - name: Uat GitOps
        run: |
          cd envs/uat/05-gitops
          terraform init
          terraform apply -auto-approve
